### ISSUE TITLE
XCode Install Additional Components

### ISSUE THREAD

**Issue by mdietz94** [wesleyan/chef-cookbooks#89]
The change you made broke XCode so now some compilations fail until you run XCode and choose to install additional components, which the Chef installer used to do automatically.

**Comment by rchristensen** [comment]
How do you know? It's not uploaded, it works fine in my testing though. I switched to having chef install each pkg (MobileDevice and MobileDeviceDev) instead of using a composed package.

--sent from my Nexus 4

On Jan 30, 2014 11:07 AM, Max Dietz notifications@github.com wrote:

The change you made broke XCode so now some compilations fail until you run XCode and choose to install additional components, which the Chef installer used to do automatically.

**Comment by mdietz94** [comment]
Oh well then I guess the current method doesn't work?  It gave me the popup on the DevMac

**Comment by rchristensen** [comment]
Yea, the current method is broke that’s why I put work into redoing how we deploy Xcode.. Lots changed with 5.0.  Thanks for the report though.. I’ll let you know when I deploy changes so you can follow up if you like.

**Comment by rchristensen** [comment]
Resolved this a while back, using the package captured from the Mac App Store, when they remotely execute a few .pkg files inside the Xcode.app directory and everything's happy.
